### PR TITLE
Netrw symlink

### PR DESCRIPTION
**Pull request by chocoelho**
Possible solution for symlink problem and also set current project based on current file.

### CODE REVIEW

**Comment by rodrigosiqueira** [comment]
ow... this one is pretty hard for me in my current level. Please, give me some days to update my knowledge about vim script :)

**Comment by tallysmartins** [comment]
this does not seems to work for me :( still got problems with symlinks

**Comment by chocoelho** [comment]
We're still considering it. We're considering how to improve it in order 
to work NERDTree like.

**Comment by rodrigosiqueira** [comment]
Revivemos esse pull ou finalizamos ele?

**Comment by chocoelho** [comment]
O Netrw possui uma limitação dele mesmo neste caso, esse problema teria que
ver como o NERDTree faz a implementação dessa feature. Se quiser se aventurar
nisso...--Carlos CoêlhoGithub: @chocoelho

**Pull request closed without merging**
